namespace TaskManagementSystem.Commands.Enums
{
    public enum CommandType
    {
        CreateTeam,
        CreatePerson,
        CreateBoard,
        CreateNewBug,
        CreateNewStory,
        CreateNewFeedback,
        AddPersonToTeam,
        ChangeBugPriority,
        ChangeBugSeverity,
        ChangeBugStatus,
        ChangeStoryPriority,
        ChangeStorySize,
        ChangeStoryStatus,
        ChangeFeedbackRating,
        ChangeFeedbackStatus,
        ShowAllPeople,
        ShowPersonActivity,
        ShowAllTeams,
        ShowTeamActivity,
        ShowAllTeamPeople,
        ShowAllTeamBoards,
        ShowBoardActivity,
        AssignTaskToPerson,
        UnassignTaskToPerson,
        AddCommentToATask,
        ListAllTasks,
        ListBugs,
        ListStories,
        ListFeedback,
        ListTasksWithAssignee
    }
}
