namespace TaskManagementSystem.Commands.Enums
{
    public enum CommandType
    {
        CreateTeam,
        CreateMember,
        CreateBoard,
        CreateNewBug,
        CreateNewStory,
        CreateNewFeedback,
        AddMemberToTeam,
        ChangeBugPriority,
        ChangeBugSeverity,
        ChangeBugStatus,
        ChangeStoryPriority,
        ChangeStorySize,
        ChangeStoryStatus,
        ChangeFeedbackRating,
        ChangeFeedbackStatus,
        ShowAllPeople,
        ShowMemberActivity,
        ShowAllTeams,
        ShowTeamActivity,
        ShowAllTeamMembers,
        ShowAllTeamBoards,
        ShowBoardActivity,
        AssignTaskToMember,
        UnAssignTaskToMember,
        AddCommentToATask,
        ListAllTasks,
        ListBugs,
        ListStories,
        ListFeedback,
        ListTasksWithAssignee
    }
}
